# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '5.4'
	pod 'CryptoSwift', '1.4.1'
	pod 'Socket.IO-Client-Swift'
  # Pods for Runner

end
